export const CARDS = [
    {
        id:1,
        image: "https://picsum.photos/400/300",
        tags: ["AI", "Productivity"],
        title: "Aaask",
        description: "Aaask is the best way to collect feedback from your team on autopilot.",
        isBookmarked: false,
    },
    {
        id:2,
        image: "https://picsum.photos/400/300",
        tags: ["AI", "Marketing", "Productivity"],
        title: "SEO Katana",
        description: "Katana helps you find your competitors top organic content, analyze it, and create unique content inspired by it for you.",
        isBookmarked: false,
    },
    {
        id:3,
        image: "https://picsum.photos/400/300",
        tags: ["AI", "Productivity", "Tooling"],
        title: "Lindo AI",
        description: "A white-label AI website builder empowering entrepreneurs and agencies to start their own web design businesses in minutes.",
        isBookmarked: false,
    },
    {
        id:4,
        image: "https://picsum.photos/400/300",
        tags: ["Code Challenge", "Learn", "Programming"],
        title: "Divize",
        description: "Learn, Write, Master: HTML/CSS Through Real UI Challenges.",
        isBookmarked: false,
    },
    {
        id:5,
        image: "https://picsum.photos/400/300",
        tags: ["Learn", "Programming", "Code challenge", "React"],
        title: "React tutorial",
        description: "Learn React in an interactive environment. Understand how React works not just how to build with React.",
        isBookmarked: false,
    },
    {
        id:6,
        image: "https://picsum.photos/400/300",
        tags: ["Learn", "Programming", "Code challenge", "JavaScript"],
        title: "Learn JavaScript",
        description: "Learn JavaScript in an interactive environment. Read short lessons, take notes, and complete challenges directly in your browser.",
        isBookmarked: false,
    },
    {
        id:7,
        image: "https://picsum.photos/400/300",
        tags: ["Open Source"],
        title: "Hubdev",
        description: "A developer resource collection with advanced semantic search powered by Vercel SDK, OpenAI, and Supabase for precise results.",
        isBookmarked: false,
    },
    {
        id:8,
        image: "https://picsum.photos/400/300",
        tags: ["Open Source"],
        title: "Opensource.builders",
        description: "Find open-source alternatives to popular software.",
        isBookmarked: false,
    },
    {
        id:9,
        image: "https://picsum.photos/400/300",
        tags: ["Performance"],
        title: "Gcore Speed Test",
        description: "Check your Internet speed and the quality of your broadband and mobile connection with our free speed testing tool.",
        isBookmarked: false,
    },
    {
        id:10,
        image: "https://picsum.photos/400/300",
        tags: ["Performance"],
        title: "PageSpeed Insights",
        description: "PageSpeed Insights analyzes the content of a web page, then generates suggestions to make that page faster.",
        isBookmarked: false,
    },
]